Ok(LineParsed { name: "BEGIN", params: None, value: "VCALENDAR" })
Ok(LineParsed { name: "CALSCALE", params: None, value: "GREGORIAN" })
Ok(LineParsed { name: "PRODID", params: None, value: "-//Example Inc.//Example Calendar//EN" })
Ok(LineParsed { name: "VERSION", params: None, value: "2.0" })
Ok(LineParsed { name: "BEGIN", params: None, value: "VEVENT" })
Ok(LineParsed { name: "DTSTAMP", params: None, value: "20080205T191224Z" })
Ok(LineParsed { name: "DTSTART", params: Some([("VALUE", ["DATE"])]), value: "20081006" })
Ok(LineParsed { name: "SUMMARY", params: None, value: "Planning meeting" })
Ok(LineParsed { name: "UID", params: None, value: "4088E990AD89CB3DBB484909" })
Ok(LineParsed { name: "BEGIN", params: None, value: "VALARM" })
Ok(LineParsed { name: "SUMMARY", params: None, value: "escaped\\, comma and\\; semicolon\\nnewline" })
Ok(LineParsed { name: "END", params: None, value: "VALARM" })
Ok(LineParsed { name: "END", params: None, value: "VEVENT" })
Ok(LineParsed { name: "END", params: None, value: "VCALENDAR" })
Ok(LineParsed { name: "BEGIN", params: None, value: "VCALENDAR" })
Ok(LineParsed { name: "ATTENDEE", params: Some([("DELEGATED-TO", ["mailto:foo7@bar", "mailto:foo8@bar"]), ("CN", ["Foo, Bar"])]), value: "foo7@bar\",\"mailto:foo8@bar\";CN=\"Foo, Bar\":mailto:foo1@bar" })
Ok(LineParsed { name: "ATTENDEE", params: Some([("DELEGATED-TO", ["mailto:foo7@bar", "mailto:foo8@bar"]), ("CN", ["Foo; Bar"])]), value: "foo7@bar\",\"mailto:foo8@bar\";CN=\"Foo; Bar\":mailto:foo2@bar" })
Ok(LineParsed { name: "ATTENDEE", params: Some([("CN", ["Foo, Bar"])]), value: "mailto:foo3@bar" })
Ok(LineParsed { name: "ATTENDEE", params: Some([("CN", ["Foo; Bar"])]), value: "mailto:foo4@bar" })
Ok(LineParsed { name: "ATTENDEE", params: Some([("DELEGATED-TO", ["mailto:foo7@bar"]), ("CN", ["Foo, Bar"])]), value: "foo7@bar\";CN=\"Foo, Bar\":mailto:foo5@bar" })
Ok(LineParsed { name: "ATTENDEE", params: Some([("DELEGATED-TO", ["mailto:foo7@bar"]), ("CN", ["Foo; Bar"])]), value: "foo7@bar\";CN=\"Foo; Bar\":mailto:foo6@bar" })
Ok(LineParsed { name: "ATTENDEE", params: Some([("ROLE", ["REQ-PARTICIPANT;foo"]), ("DELEGATED-FROM", ["mailto:bar@baz.com"]), ("PARTSTAT", ["ACCEPTED"]), ("RSVP", ["TRUE"])]), value: "bar@baz.com\";PARTSTAT=ACCEPTED;RSVP=TRUE:mailto:foo@bar.com" })
Ok(LineParsed { name: "X-FOO", params: Some([("PARAM1", ["VAL1"])]), value: "FOO;BAR" })
Ok(LineParsed { name: "X-FOO2", params: Some([("PARAM1", ["VAL1"]), ("PARAM2", ["VAL2"])]), value: "FOO;BAR" })
Ok(LineParsed { name: "X-BAR", params: Some([("PARAM1", ["VAL1:FOO"])]), value: "FOO\":BAZ;BAR" })
Ok(LineParsed { name: "X-BAZ", params: Some([("PARAM1", ["VAL1:FOO"]), ("PARAM2", ["VAL2"])]), value: "FOO\";PARAM2=VAL2:BAZ;BAR" })
Ok(LineParsed { name: "X-BAZ2", params: Some([("PARAM1", ["VAL1"]), ("PARAM2", ["VAL2:FOO"])]), value: "FOO\":BAZ;BAR" })
Ok(LineParsed { name: "END", params: None, value: "VCALENDAR" })
