Ok(LineParsed { name: "BEGIN", params: None, value: "VCARD" })
Ok(LineParsed { name: "VERSION", params: None, value: "4.0" })
Ok(LineParsed { name: "ADR", params: Some([("TYPE", ["work"])]), value: "pobox;apt;street;city;state;zipcode;country" })
Ok(LineParsed { name: "ANNIVERSARY", params: None, value: "19960415" })
Ok(LineParsed { name: "BDAY", params: None, value: "--0203" })
Ok(LineParsed { name: "CALADRURI", params: None, value: "http://example.com/calendar/jdoe" })
Ok(LineParsed { name: "CALURI", params: Some([("MEDIATYPE", ["text/calendar"])]), value: "ftp://ftp.example.com/calA.ics" })
Ok(LineParsed { name: "CLIENTPIDMAP", params: None, value: "1;urn:uuid:3df403f4-5924-4bb7-b077-3c711d9eb34b" })
Ok(LineParsed { name: "EMAIL", params: Some([("TYPE", ["work"])]), value: "jqpublic@xyz.example.com" })
Ok(LineParsed { name: "FBURL", params: Some([("MEDIATYPE", ["text/calendar"])]), value: "ftp://example.com/busy/project-a.ifb" })
Ok(LineParsed { name: "FN", params: None, value: "J. Doe" })
Ok(LineParsed { name: "GENDER", params: None, value: "M;Fellow" })
Ok(LineParsed { name: "GEO", params: None, value: "geo:37.386013\\,-122.082932" })
Ok(LineParsed { name: "IMPP", params: Some([("PREF", ["1"])]), value: "xmpp:alice@example.com" })
Ok(LineParsed { name: "KEY", params: None, value: "http://www.example.com/keys/jdoe.cer" })
Ok(LineParsed { name: "KIND", params: None, value: "individual" })
Ok(LineParsed { name: "LANG", params: Some([("PREF", ["1"])]), value: "fr" })
Ok(LineParsed { name: "LOGO", params: None, value: "http://www.example.com/pub/logos/abccorp.jpg" })
Ok(LineParsed { name: "MEMBER", params: None, value: "urn:uuid:03a0e51f-d1aa-4385-8a53-e29025acd8af" })
Ok(LineParsed { name: "N", params: None, value: "Stevenson;John;Philip,Paul;Dr.;Jr.,M.D.,A.C.P." })
Ok(LineParsed { name: "NICKNAME", params: Some([("TYPE", ["work"])]), value: "Boss" })
Ok(LineParsed { name: "NOTE", params: None, value: "This fax number is operational 0800 to 1715 EST\\, Mon-Fri" })
Ok(LineParsed { name: "ORG", params: None, value: "ABC\\, Inc.;North American Division;Marketing" })
Ok(LineParsed { name: "PHOTO", params: None, value: "http://www.example.com/pub/photos/jqpublic.gif" })
Ok(LineParsed { name: "RELATED", params: Some([("TYPE", ["friend"])]), value: "urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6" })
Ok(LineParsed { name: "REV", params: None, value: "19951031T222710Z" })
Ok(LineParsed { name: "ROLE", params: None, value: "Project Leader" })
Ok(LineParsed { name: "SOUND", params: None, value: "CID:JOHNQPUBLIC.part8.19960229T080000.xyzMail@example.com" })
Ok(LineParsed { name: "SOURCE", params: None, value: "ldap://ldap.example.com/cn=Babs%20Jensen\\,%20o=Babsco\\,%20c=US" })
Ok(LineParsed { name: "TEL", params: Some([("VALUE", ["uri"]), ("TYPE", ["home"])]), value: "tel:+33-01-23-45-67" })
Ok(LineParsed { name: "TITLE", params: None, value: "Research Scientist" })
Ok(LineParsed { name: "TZ", params: Some([("VALUE", ["utc-offset"])]), value: "-0500" })
Ok(LineParsed { name: "XML", params: None, value: "<html xmlns=\"http://www.w3.org/1999/xhtml\"></html>" })
Ok(LineParsed { name: "END", params: None, value: "VCARD" })
