Ok(LineParsed { name: "BEGIN", params: None, value: Some("VCARD") })
Ok(LineParsed { name: "VERSION", params: None, value: Some("4.0") })
Ok(LineParsed { name: "ADR", params: Some([("TYPE", ["work"])]), value: Some("pobox;apt;street;city;state;zipcode;country") })
Ok(LineParsed { name: "ANNIVERSARY", params: None, value: Some("19960415") })
Ok(LineParsed { name: "BDAY", params: None, value: Some("--0203") })
Ok(LineParsed { name: "CALADRURI", params: None, value: Some("http://example.com/calendar/jdoe") })
Ok(LineParsed { name: "CALURI", params: Some([("MEDIATYPE", ["text/calendar"])]), value: Some("ftp://ftp.example.com/calA.ics") })
Ok(LineParsed { name: "CLIENTPIDMAP", params: None, value: Some("1;urn:uuid:3df403f4-5924-4bb7-b077-3c711d9eb34b") })
Ok(LineParsed { name: "EMAIL", params: Some([("TYPE", ["work"])]), value: Some("jqpublic@xyz.example.com") })
Ok(LineParsed { name: "FBURL", params: Some([("MEDIATYPE", ["text/calendar"])]), value: Some("ftp://example.com/busy/project-a.ifb") })
Ok(LineParsed { name: "FN", params: None, value: Some("J. Doe") })
Ok(LineParsed { name: "GENDER", params: None, value: Some("M;Fellow") })
Ok(LineParsed { name: "GEO", params: None, value: Some("geo:37.386013\\,-122.082932") })
Ok(LineParsed { name: "IMPP", params: Some([("PREF", ["1"])]), value: Some("xmpp:alice@example.com") })
Ok(LineParsed { name: "KEY", params: None, value: Some("http://www.example.com/keys/jdoe.cer") })
Ok(LineParsed { name: "KIND", params: None, value: Some("individual") })
Ok(LineParsed { name: "LANG", params: Some([("PREF", ["1"])]), value: Some("fr") })
Ok(LineParsed { name: "LOGO", params: None, value: Some("http://www.example.com/pub/logos/abccorp.jpg") })
Ok(LineParsed { name: "MEMBER", params: None, value: Some("urn:uuid:03a0e51f-d1aa-4385-8a53-e29025acd8af") })
Ok(LineParsed { name: "N", params: None, value: Some("Stevenson;John;Philip,Paul;Dr.;Jr.,M.D.,A.C.P.") })
Ok(LineParsed { name: "NICKNAME", params: Some([("TYPE", ["work"])]), value: Some("Boss") })
Ok(LineParsed { name: "NOTE", params: None, value: Some("This fax number is operational 0800 to 1715 EST\\, Mon-Fri") })
Ok(LineParsed { name: "ORG", params: None, value: Some("ABC\\, Inc.;North American Division;Marketing") })
Ok(LineParsed { name: "PHOTO", params: None, value: Some("http://www.example.com/pub/photos/jqpublic.gif") })
Ok(LineParsed { name: "RELATED", params: Some([("TYPE", ["friend"])]), value: Some("urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6") })
Ok(LineParsed { name: "REV", params: None, value: Some("19951031T222710Z") })
Ok(LineParsed { name: "ROLE", params: None, value: Some("Project Leader") })
Ok(LineParsed { name: "SOUND", params: None, value: Some("CID:JOHNQPUBLIC.part8.19960229T080000.xyzMail@example.com") })
Ok(LineParsed { name: "SOURCE", params: None, value: Some("ldap://ldap.example.com/cn=Babs%20Jensen\\,%20o=Babsco\\,%20c=US") })
Ok(LineParsed { name: "TEL", params: Some([("VALUE", ["uri"]), ("TYPE", ["home"])]), value: Some("tel:+33-01-23-45-67") })
Ok(LineParsed { name: "TITLE", params: None, value: Some("Research Scientist") })
Ok(LineParsed { name: "TZ", params: Some([("VALUE", ["utc-offset"])]), value: Some("-0500") })
Ok(LineParsed { name: "XML", params: None, value: Some("<html xmlns=\"http://www.w3.org/1999/xhtml\"></html>") })
Ok(LineParsed { name: "END", params: None, value: Some("VCARD") })
